"""make_vendor_id_nullable_on_reorder_recommendations

Revision ID: cf2574ef4d5f
Revises: 599ad87e3afd
Create Date: 2026-03-10 22:19:43.328876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf2574ef4d5f'
down_revision: Union[str, Sequence[str], None] = '599ad87e3afd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reorder_recommendations', 'vendor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reorder_recommendations', 'vendor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
